### ISSUE TITLE
Not updating

### ISSUE THREAD

**Issue by bigattck** [fr33mind/Belle#11]
there is a huge bug where i add the actions, buttons and everything but it never updates in google chrome, internet explorer or anywhere. i cant make a game with this kind of bug.

**Comment by fr33mind** [comment]
Hi,
Thanks for taking the time to report. The behaviour you describe is really strange, are you pressing the run button everytime you make a change? If not, you need to do that.

**Comment by bigattck** [comment]
@fr33mind I did but still didnt help, now the odd part is that every time i shutdown the computer it updates the game data. i deleted the game data with the engine and made a new one but again the same problem happen where it does not update on mistakes i made.

**Comment by fr33mind** [comment]
@bigattck You tried to create a new project and it still wouldn't run the updated game in the browser even after you pressed the run button? And what kind of mistakes are you talking about? Also can you try to export your game and open the index.html in the exported folder?

**Comment by fr33mind** [comment]
@bigattck So can i close this ticket or the problem persists?
