### ISSUE TITLE
Game cant run only show's a blank screen

### ISSUE THREAD

**Issue by donjjp** [fr33mind/Belle#28]
Help! my game cant run, i dont know what happend's to him it only show's a blank screen
[2019-08-11](https://user-images.githubusercontent.com/53996822/62834297-1dff0500-bc18-11e9-8ace-450d76f96eda.png)

**Comment by fr33mind** [comment]
Hey, thanks for trying out Belle. Just with that image i can't help much. Have you tried opening on Chrome or Firefox to see if it happens too?
Other than that i don't know, but if you could send me the game project so i can see, it would help a lot. Thanks.

**Comment by donjjp** [comment]
> Hey, thanks for trying out Belle. Just with that image i can't help much. Have you tried opening on Chrome or Firefox to see if it happens too?
> Other than that i don't know, but if you could send me the game project so i can see, it would help a lot. Thanks.

Hello sorry to reply late but i tried for example selecting ''Belle.exe'' from Winrar over and over when that problem happend's but it only shows the same blank screen with a text saying

FPS: Dummy

It's like the program saying FUCK YOU!

![Dummy](https://user-images.githubusercontent.com/53996822/63066237-16b94f00-bed7-11e9-879e-a642dee7b813.png)

**Comment by fr33mind** [comment]
Hey. Sorry i don't understand, are you opening Belle.exe directly from winrar?
Anyway i said to try running your game in Firefox or Chrome to see if the same happens. To do that, in the game window that you just showed, you can click on "View", then check the "ToolBar" item. A toolbar with the link will appear and you just need to copy that and paste in Firefox or Chrome.

Regarding the text i never thought of that that way, but i see your point. However it's not the program telling you are a dummy. It's just a thing that's used by the program to test stuff. Normally you shouldn't see any of that. The same goes for "FPS:", it's another internal thing.

**Comment by donjjp** [comment]
> Hey. Sorry i don't understand, are you opening Belle.exe directly from winrar?
> Anyway i said to try running your game in Firefox or Chrome to see if the same happens. To do that, in the game window that you just showed, you can click on "View", then check the "ToolBar" item. A toolbar with the link will appear and you just need to copy that and paste in Firefox or Chrome.
> 
> Regarding the text i never thought of that that way, but i see your point. However it's not the program telling you are a dummy. It's just a thing that's used by the program to test stuff. Normally you shouldn't see any of that. The same goes for "FPS:", it's another internal thing.

Ok i take your advice to copy and paste the toolbar's link to Chrome and... IT WORKS!

-Thank You!

**Comment by fr33mind** [comment]
Good to know. Although it's strange it's giving you that weird issue on the built-in browser, but not in Chrome or other. Anyway if using Chrome works for you then it's all good. Actually that's where people will play your game, that and other popular browsers. The built-in browser is just for convenience during development.

Since everything is good, i'm closing this issue, anything else let me know.
